#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, The OpenROAD Authors
#
# HotSpot oracle cross-validation harness for therm3d (T4b).
#
# Runs our in-tree solver (via the `dump_thermal_stack` command) and the HotSpot
# 7.0 thermal solver on the SAME synthetic N-die stack, then compares per-layer
# and peak temperature and R_th. HotSpot is an external ORACLE: nothing is linked
# or ported -- this script independently emits HotSpot's documented input formats
# (formats are data, not copyrightable expression).
#
# Alignment between the two models:
#   * Layer order is REVERSED. Our layer 0 is the heat sink (Dirichlet); HotSpot
#     attaches its sink to the HIGHEST-numbered layer and leaves layer 0 as the
#     adiabatic far face. So our layer i -> HotSpot layer (M-1-i).
#   * HotSpot LCF field 5 is thermal resistivity = 1/k.
#   * HotSpot's convective package is degenerated into a near-isothermal sink at
#     ambient = T_bc (tiny TIM/spreader/sink/convection resistances, chip-sized
#     high-conductivity plates) to approximate our isothermal Dirichlet boundary.
#     The bottom face is adiabatic via -model_secondary 0, matching our model.

import os
import re
import subprocess
import sys
import tempfile

OPENROAD = os.path.expanduser("~/workspace/OpenROAD-therm3d/build/bin/openroad")
HOTSPOT = os.path.expanduser("~/workspace/HotSpot/hotspot")
HERE = os.path.dirname(os.path.abspath(__file__))
KELVIN = 273.15


def run_our_solver(num_dies, bond_type):
    """Run dump_thermal_stack and parse the DUMP_* block into a dict."""
    with tempfile.NamedTemporaryFile("w", suffix=".tcl", delete=False) as f:
        f.write(f"dump_thermal_stack -num_dies {num_dies} -bond_type {bond_type}\n")
        path = f.name
    out = subprocess.run([OPENROAD, "-no_init", "-exit", path],
                         capture_output=True, text=True).stdout
    os.unlink(path)
    stack = {"layers": []}
    for line in out.splitlines():
        for tag in ("DUMP_BEGIN", "DUMP_LAYER", "DUMP_RESULT"):
            if tag in line:
                fields = {}
                for kv in line.split(tag, 1)[1].split():
                    k, v = kv.split("=", 1)
                    fields[k] = v
                if tag == "DUMP_LAYER":
                    stack["layers"].append(fields)
                else:
                    stack.update(fields)
    return stack


def write_hotspot_inputs(stack, workdir):
    """Generate stack.lcf / *.flp / stack.ptrace / stack.config in workdir."""
    layers = stack["layers"]
    m = len(layers)
    footprint = float(stack["footprint_um"]) * 1e-6
    t_bc = float(stack["t_bc_c"])
    nx, ny = int(stack["nx"]), int(stack["ny"])

    die_blocks = []           # (block_name, power_w) for the ptrace
    lcf = ["# Auto-generated by therm3d T4b harness; layers REVERSED.",
           "# HotSpot layer 0 = our far (adiabatic) face; highest = heat sink."]
    for h in range(m):
        our = m - 1 - h        # our layer index for HotSpot layer h
        layer = layers[our]
        is_die = layer["kind"] == "die"
        power = float(layer["power_w"])
        name = (f"die{our}" if is_die else f"bond{our}")
        flp = f"layer{h}.flp"
        with open(os.path.join(workdir, flp), "w") as f:
            f.write(f"{name}\t{footprint:.9g}\t{footprint:.9g}\t0.0\t0.0\n")
        resistivity = 1.0 / float(layer["kz"])     # LCF field 5 = 1/k
        power_yn = "Y" if (is_die and power > 0.0) else "N"
        lcf += [str(h), "Y", power_yn,
                f"{float(layer['vhc']):.6e}", f"{resistivity:.6e}",
                f"{float(layer['thickness_m']):.6e}", flp, ""]
        if is_die and power > 0.0:
            die_blocks.append((name, power))
    with open(os.path.join(workdir, "stack.lcf"), "w") as f:
        f.write("\n".join(lcf) + "\n")

    with open(os.path.join(workdir, "stack.ptrace"), "w") as f:
        f.write("\t".join(n for n, _ in die_blocks) + "\n")
        f.write("\t".join(f"{p:.6g}" for _, p in die_blocks) + "\n")

    ambient = t_bc + KELVIN
    # Near-isothermal sink at ambient = T_bc: negligible TIM/spreader/sink/
    # convection resistance, chip-sized high-k plates, adiabatic bottom.
    config = [
        "-t_chip 1.0e-4", "-k_chip 100.0", "-p_chip 1.75e6",
        "-thermal_threshold 1000.0",
        # Near-isothermal sink at ambient: low (but non-degenerate) package
        # resistance, high-conductivity plates slightly larger than the chip
        # (chip-sized plates make SuperLU singular). The small residual package
        # rise is removed by the internal-delta-T comparison.
        "-c_convec 140.4", "-r_convec 5.0e-3",
        f"-s_sink {footprint * 1.6:.9g}", "-t_sink 1.0e-4", "-k_sink 400.0",
        "-p_sink 3.55e6",
        f"-s_spreader {footprint * 1.3:.9g}", "-t_spreader 1.0e-4",
        "-k_spreader 400.0", "-p_spreader 3.55e6",
        "-t_interface 1.0e-7", "-k_interface 10.0", "-p_interface 4.0e6",
        "-model_secondary 0",
        f"-ambient {ambient:.4f}", f"-init_temp {ambient:.4f}",
        "-model_type grid", f"-grid_rows {ny}", f"-grid_cols {nx}",
        "-grid_map_mode center",
    ]
    with open(os.path.join(workdir, "stack.config"), "w") as f:
        f.write("\n".join(config) + "\n")
    return m


def run_hotspot(workdir):
    cmd = [HOTSPOT, "-c", "stack.config", "-p", "stack.ptrace",
           "-grid_layer_file", "stack.lcf", "-model_type", "grid",
           "-detailed_3D", "on",
           "-grid_steady_file", "out.grid.steady", "-steady_file", "out.steady"]
    res = subprocess.run(cmd, cwd=workdir, capture_output=True, text=True)
    return res, os.path.join(workdir, "out.steady")


def parse_hotspot(steady_path):
    """Map HotSpot layer number -> peak temperature [°C]."""
    temps = {}
    pat = re.compile(r"^layer_(\d+)_\S+\s+([\d.eE+-]+)")
    with open(steady_path) as f:
        for line in f:
            mobj = pat.match(line)
            if mobj:
                h = int(mobj.group(1))
                t = float(mobj.group(2)) - KELVIN
                temps[h] = max(temps.get(h, -1e9), t)
    return temps


def monotonic(seq):
    return all(seq[i] < seq[i + 1] for i in range(len(seq) - 1))


def main():
    ns = [int(x) for x in (sys.argv[1:] or ["4", "5", "6"])]
    bond = "microbump"
    print(f"therm3d vs HotSpot 7.0 oracle  (bond={bond}, N={ns})\n")
    rows = []
    detail_done = False
    for n in ns:
        stack = run_our_solver(n, bond)
        workdir = os.path.join(HERE, f"work_n{n}")
        os.makedirs(workdir, exist_ok=True)
        m = write_hotspot_inputs(stack, workdir)
        res, steady = run_hotspot(workdir)
        if not os.path.exists(steady):
            print(f"N={n}: HotSpot FAILED\n--- stderr ---\n{res.stderr[-1200:]}")
            return
        hs = parse_hotspot(steady)
        hs_our = {m - 1 - h: t for h, t in hs.items()}  # -> our layer index
        t_bc = float(stack["t_bc_c"])
        total_p = float(stack["total_power_w"])
        our_peak, our_rth = float(stack["peak_c"]), float(stack["rth_kw"])
        hs_peak = max(hs_our.values())
        hs_rth = (hs_peak - t_bc) / total_p
        our_sink = float(stack["layers"][0]["peakT_c"])  # our layer 0 = sink side
        hs_sink = hs_our.get(0, float("nan"))
        rows.append((n, our_rth, our_peak, hs_rth, hs_peak,
                     our_peak - our_sink, hs_peak - hs_sink, total_p))
        if not detail_done:
            print(f"per-layer peak T [°C], N={n} (our layer idx; 0 = sink side):")
            print(f"  {'idx':>3} {'kind':>5} {'ours':>9} {'hotspot':>9} {'Δ':>8}")
            for i in range(m):
                ours = float(stack["layers"][i]["peakT_c"])
                hv = hs_our.get(i, float("nan"))
                kind = stack["layers"][i]["kind"]
                print(f"  {i:3d} {kind:>5} {ours:9.3f} {hv:9.3f} {hv - ours:8.3f}")
            print()
            detail_done = True

    print("absolute  (ours = isothermal Dirichlet BC; HotSpot = convective package):")
    print(f"  {'N':>3} {'ourRth':>8} {'hsRth':>8} {'Rth Δ%':>7} "
          f"{'ourPeak':>9} {'hsPeak':>9} {'pk Δ°C':>7}")
    for (n, orth, opk, hrth, hpk, oint, hint, tp) in rows:
        print(f"  {n:3d} {orth:8.4f} {hrth:8.4f} {(hrth - orth) / orth * 100:7.1f} "
              f"{opk:9.3f} {hpk:9.3f} {hpk - opk:7.3f}")
    print("\ninternal stack ΔT = peak - sink-side die  (BC-independent — the clean check):")
    print(f"  {'N':>3} {'ourΔT':>8} {'hsΔT':>8} {'ΔT Δ%':>7} "
          f"{'ourRth_i':>9} {'hsRth_i':>9}")
    for (n, orth, opk, hrth, hpk, oint, hint, tp) in rows:
        print(f"  {n:3d} {oint:8.3f} {hint:8.3f} {(hint - oint) / oint * 100:7.2f} "
              f"{oint / tp:9.4f} {hint / tp:9.4f}")
    print(f"\nR_th monotonic — ours: {monotonic([r[1] for r in rows])}, "
          f"HotSpot: {monotonic([r[3] for r in rows])}")
    print("hottest layer — both models: our last layer (top die, "
          "farthest from sink)")


if __name__ == "__main__":
    main()
